name: 'Run UI tests'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  details-tab:
    runs-on: [ubuntu-latest]
    name: Details tab UI tests

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build warnings plugin and download dependencies
        run: mvn -V -ntp verify -Pskip --file plugin/pom.xml -Dgpg.skip
      - name: Run UI tests for the details tabs
        env:
          BROWSER: firefox-container
        run: mvn -V -ntp test --file ui-tests/pom.xml -Dtest=DetailsTabUiTest -Dgpg.skip

  dashboard-view:
    runs-on: [ubuntu-latest]
    name: Dashboard view UI tests

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build warnings plugin and download dependencies
        run: mvn -V -ntp verify -Pskip --file plugin/pom.xml -Dgpg.skip
      - name: Run UI tests for the dashboard view
        env:
          BROWSER: firefox-container
        run: mvn -V -ntp test --file ui-tests/pom.xml -Dtest=DashboardViewPortletUiTest -Dgpg.skip

  freestyle-configuration:
    runs-on: [ubuntu-latest]
    name: Freestyle configuration UI tests

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build warnings plugin and download dependencies
        run: mvn -V -ntp verify -Pskip --file plugin/pom.xml -Dgpg.skip
      - name: Run UI tests for the freestyle configuration
        env:
          BROWSER: firefox-container
        run: mvn -V -ntp test --file ui-tests/pom.xml -Dtest=FreeStyleConfigurationUiTest -Dgpg.skip

  pipeline-snippet-generator:
    runs-on: [ubuntu-latest]
    name: Pipeline snippet configurator UI tests

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build warnings plugin and download dependencies
        run: mvn -V -ntp verify -Pskip --file plugin/pom.xml -Dgpg.skip
      - name: Run UI tests for the pipeline snippet configurator
        env:
          BROWSER: firefox-container
        run: mvn -V -ntp test --file ui-tests/pom.xml -Dtest=SnippetGeneratorUiTest -Dgpg.skip

